IDENTIFIER = "identifier"
TITLE = "title"
COVER_DATE = "cover_date"
CITED_COUNT = "cited_count"
SUBTYPE_DESCRIPTION = "subtype_description"
OPEN_ACCESS_FLAG = "open_access_flag"
AUTHORS = "authors"

FILENAME_SCOPUS_QUERY = "paper_information_scopus"
FILENAME_BASE_NOT_SCOPUS = "paper_information_"

FILEPATH_OUTPUT_SCOPUS_SEARCH = "scraper/output/"
FILEPATH_INPUT_OTHER_SEARCH = "scraper/input/"
FILENAME_BASE_SEARCH = "ids_scopus_"
FILENAME_ACM = "acm"
FILENAME_IEEE = "ieee"
FILENAME_SCIENCE_DIRECT = "science_direct"
